---
title: "Alfa_Cats"
author: "Frederik Hilbert"
date: "2026-05-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(phyloseq)
library(vegan)
library(dplyr)
library(tibble)
library(purrr)
library(stringr)
library(ggplot2)
library(tidyverse)
library(ggh4x)
library(lme4)
library(lmerTest)
library(broom.mixed)
library(lme4)
library(picante)
```
## Loading data

```{r Loading Data}
file_path <- "/home/hilbert/Desktop/Uni/Meta_and_Micro/NBIB25004U-Metagenomics-2026/group-project-group-7/project/data/molecular_ecology_17695.rds"

Cats <- readRDS(file_path)

Cats_ps <- Cats$phyloseq
Cats_ps
```


## Alfa Diversitet All methords 
### Shannon

```{r calculate-shannon}
# Calculate Shannon diversity for all samples
shannon <- estimate_richness(
  Cats_ps,
  measures = "Shannon"
)

head(shannon)
```



```{r plot-shannon-basic, fig.width=8, fig.height=5}
plot_richness(
  Cats_ps,
  measures = "Shannon"
)
```


```{r plot-shannon-by-body-site, fig.width=9, fig.height=5}
plot_richness(
  Cats_ps,
  measures = "Shannon",
  x = "origin"
)
```

```{r build-alpha-diversity-table}
ps_pa <- transform_sample_counts(Cats_ps, function(x) {ifelse(x > 0, 1, 0)})

# Calculate Shannon diversity
shannon <- estimate_richness(
  Cats_ps,
  measures = "Shannon"
) %>%
  rownames_to_column("sample_id")

# Calculate observed richness
observed <- estimate_richness(
  ps_pa,
  measures = "Observed"
) %>%
  rownames_to_column("sample_id")

# Extract sample metadata
sample_df <- sample_data(Cats_ps) %>%
  data.frame() %>%
  rownames_to_column("sample_id")

# Combine diversity estimates and metadata
alpha_diversity <- inner_join(
  shannon,
  observed,
  by = "sample_id"
) %>%
  inner_join(
    sample_df,
    by = "sample_id"
  )
```
```{r}
head(alpha_diversity)
```

```{r kruskal-shannon}
kruskal_shannon <- kruskal.test(
  Shannon ~ location,
  data = alpha_diversity
)

kruskal_shannon
```
```{r kruskal-shannon}
kruskal_shannon <- kruskal.test(
  Shannon ~ origin,
  data = alpha_diversity
)

kruskal_shannon
```

```{r pairwise-wilcoxon-shannon}
pw_shannon <- pairwise.wilcox.test(
  x = alpha_diversity$Shannon,
  g = alpha_diversity$location,
  p.adjust.method = "BH"
)

pw_shannon
```

```{r shannon-boxplot, fig.width=8, fig.height=5}
ggplot(alpha_diversity, aes(x = location, y = Shannon)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  theme_bw()
```


```{r spearman-depth-shannon}
cor.test(
  alpha_diversity$Observed,
  alpha_diversity$Shannon,
  method = "spearman"
)
```
## Observed richness

```{r}
# Calculate Observed richness for all samples
observed <- estimate_richness(
  ps_pa,
  measures = "Observed"
)

head(observed)
```

```{r}
plot_richness(ps_pa, measures = "Observed")
```

```{r}
# Extract sample metadata
sample_df <- sample_data(Cats_ps) %>%
  data.frame() %>%
  rownames_to_column("sample_id")

# Combine observed richness estimates and metadata
alpha_observed <- observed %>%
  rownames_to_column("sample_id") %>%
  inner_join(
    sample_df,
    by = "sample_id"
  )

head(alpha_observed)
```

```{r}
kruskal_obs_location <- kruskal.test(
  Observed ~ location,
  data = alpha_observed
)

kruskal_obs_location
```

```{r}
kruskal_obs_origin <- kruskal.test(
  Observed ~ origin,
  data = alpha_observed
)

kruskal_obs_origin
```

```{r}
pw_observed <- pairwise.wilcox.test(
  x = alpha_observed$Observed,
  g = alpha_observed$location,
  p.adjust.method = "BH"
)

pw_observed
```

```{r}
ggplot(alpha_observed, aes(x = location, y = Observed)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  theme_bw()
```

## Phylogentic Diversity (PD)

```{r}
# Faith's PD requires samples to be rows in the matrix
otu_mat <- as(otu_table(Cats_ps), "matrix")
if (taxa_are_rows(Cats_ps)) {
  otu_mat <- t(otu_mat)
}

# Calculate Faith's Phylogenetic Diversity
pd_calculated <- pd(otu_mat, phy_tree(Cats_ps), include.root = FALSE)

head(pd_calculated)
```

```{r}
# Creating an alpha dataframe specifically for the basic plots
pd_basic_df <- pd_calculated %>% 
  rownames_to_column("sample_id") %>% 
  inner_join(sample_df, by = "sample_id")

ggplot(pd_basic_df, aes(x = sample_id, y = PD)) +
  geom_point() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vtext = 0.5, hjust = 1)) +
  labs(x = "Samples", y = "Phylogenetic Diversity (PD)")
```

```{r}
ggplot(pd_basic_df, aes(x = origin, y = PD)) +
  geom_point(position = position_jitter(width = 0.1)) +
  theme_bw() +
  labs(x = "origin", y = "Phylogenetic Diversity (PD)")
```

```{r}
# Combine PD estimates and metadata
alpha_pd <- pd_calculated %>%
  rownames_to_column("sample_id") %>%
  inner_join(
    sample_df,
    by = "sample_id"
  )

head(alpha_pd)
```

```{r}
kruskal_pd_location <- kruskal.test(
  PD ~ location,
  data = alpha_pd
)

kruskal_pd_location
```

```{r}
kruskal_pd_origin <- kruskal.test(
  PD ~ origin,
  data = alpha_pd
)

kruskal_pd_origin
```

```{r}
pw_pd <- pairwise.wilcox.test(
  x = alpha_pd$PD,
  g = alpha_pd$location,
  p.adjust.method = "BH"
)

pw_pd
```

```{r}
ggplot(alpha_pd, aes(x = location, y = PD)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  theme_bw() +
  labs(y = "Phylogenetic Diversity (PD)")
```

```{r}
cor.test(
  alpha_pd$SR,
  alpha_pd$PD,
  method = "spearman"
)
```


